### ISSUE TITLE
a manual update is required - exited with code 255

### ISSUE THREAD

**Issue by skupfer** [galexrt/docker-sinusbot#25]
Trying to set this up, I always receive code 255 and the bot restarts... Same happens with `docker run`

```
version: "3.4"
services:

  sinusbot:
    image: galexrt/sinusbot:latest
    ports:
      - "127.0.0.1:8087:8087"
    volumes:
      - sinusbot-data-vol1:/sinusbot/data
      - sinusbot-scripts-vol1:/sinusbot/scripts
    restart: always

volumes:
  sinusbot-data-vol1:
  sinusbot-scripts-vol1:
```

```
docker-compose up -d && docker-compose logs -f sinusbot
Creating network "sinusbot_default" with the default driver
Creating volume "sinusbot_sinusbot-data-vol1" with default driver
Creating volume "sinusbot_sinusbot-scripts-vol1" with default driver
Creating sinusbot_sinusbot_1 ...
Creating sinusbot_sinusbot_1 ... done
Attaching to sinusbot_sinusbot_1
sinusbot_1  | -> Updating sinusbot user and group id if necessary ...
sinusbot_1  | -> Correcting file and mount point permissions ...
sinusbot_1  | => Corrected mount point permissions.
sinusbot_1  | -> Checking if scripts directory is empty
sinusbot_1  | -> Copying original sinusbot scripts to volume ...
sinusbot_1  | => Sinusbot scripts copied.
sinusbot_1  | -> Checking for old data location ...
sinusbot_1  | => You are good to go! You are already using the new data directory, located at "/sinusbot/data".
sinusbot_1  | => Updating Youtube-dl...
sinusbot_1  | Updating to version 2017.12.02 ...
sinusbot_1  | Updated youtube-dl. Restart youtube-dl to use the new version.
sinusbot_1  | => Updated youtube-dl with exit code 0
sinusbot_1  | => Starting SinusBot (https://sinusbot.com) by Michael Friese ...
sinusbot_1  | 2017/11/24 17:09:19 X [MAIN] Starting up fake x-server...
sinusbot_1  |  ___ ___ _  _ _   _ ___ ___  ___ _____  BETA
sinusbot_1  | / __|_ _| \| | | | / __| _ )/ _ \_   _|
sinusbot_1  | \__ \| || .` | |_| \__ \ _ \ (_) || |
sinusbot_1  | |___/___|_|\_|\___/|___/___/\___/ |_|
sinusbot_1  |
sinusbot_1  | Version: 0.10.8-71ba94b
sinusbot_1  | (C) 2013-2017 Michael Friese. All rights reserved.
sinusbot_1  |
sinusbot_1  | 2017/11/24 17:09:19 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin advertising.js
sinusbot_1  | 2017/11/24 17:09:19 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin alonemode.js
sinusbot_1  | 2017/11/24 17:09:19 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin bookmark.js
sinusbot_1  | 2017/11/24 17:09:19 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin followme.js
sinusbot_1  | 2017/11/24 17:09:19 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin norecording.js
sinusbot_1  | 2017/11/24 17:09:19 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin rememberChannel.js
sinusbot_1  | 2017/11/24 17:09:19 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin welcome.js
sinusbot_1  | a manual update is required
sinusbot_sinusbot_1 exited with code 255
```
